version: '3.8'
services: 
    employee-service:
        build: 
            context: .
            dockerfile: Dockerfile
        environment: 
            - OTEL_METRICS_EXPORTER=prometheus
            - OTEL_EXPORTER_PROMETHEUS_PORT=9464
            - OTEL_TRACES_EXPORTER=jaeger
            - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250
        ports: 
            - "8111:8080"
            - "9464:9464"
    jaeger:
        image: jaegertracing/all-in-one:1.23
        ports: 
            - "16686:16686"
        expose: 
            - "14250"
    prometheus:
        image: prom/prometheus
        ports: 
            - "9090:9090"
        volumes: 
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
